trigger:
  - main  # ou la branche que tu veux surveiller

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-Dmaven.test.failure.ignore=true'
      publishJUnitResults: true
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    displayName: 'Build with Maven'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/target'
      Contents: '*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'pharma-app'
      publishLocation: 'Container'
